### ISSUE TITLE
macOS - OpenGL 1.1 HAL option not available on recent builds

### ISSUE THREAD

**Issue by aroenai** [isledecomp/isle-portable#519]
Builds after 6/27/25 no longer have the OpenGL 1.1 HAL as a selectable option using the same build environment on macOS with Apple Silicon processors.

**Comment by aroenai** [comment]
Appears to have started after e2ff65c

**Comment by AJenbo** [comment]
Hm unfortunately I don't have a Mac to test with, does this issue still happen if you don't make the test window hidden? Can the game still be made to use opengl by editing the config?

**Comment by aroenai** [comment]
> Hm unfortunately I don't have a Mac to test with, does this issue still happen if you don't make the test window hidden? Can the game still be made to use opengl by editing the config?

If you edit the isle.ini file manually for OpenGL, the game uses the SDL3 GPU HAL (credits flicker, which doesn't happen on OpenGL). If you do a quick and dirty "git revert e2ff65c" it works normally (there's conflicts on miniwin/src/d3drm/backends/opengles2/renderer.cpp but GLESv2 doesn't work on Mac anyway).

**Comment by AJenbo** [comment]
Ok, then someone on macOS should look in to what causes it to fail to initialize after the change since it's not simply a question about the test window which is what that commit aimed to address.

**Comment by AJenbo** [comment]
My best guess is that this happens because because macOS doesn't allow OpenGL to use a window after it's been interacted with by Metal. Can you try and add a return before this line and see if that allows you to set OpenGL as the renderer.

https://github.com/isledecomp/isle-portable/blob/c6b94dabcf1a75c1b757547e2325a6b4c7ba0f48/miniwin/src/internal/d3drmrenderer_sdl3gpu.h#L123

> SDL3 GPU HAL (credits flicker)

This has been addressed by the way

**Comment by aroenai** [comment]
> My best guess is that this happens because because macOS doesn't allow OpenGL to use a window after it's been interacted with by Metal. Can you try and add a return before this line and see if that allows you to set OpenGL as the renderer.
> 
> [isle-portable/miniwin/src/internal/d3drmrenderer_sdl3gpu.h](https://github.com/isledecomp/isle-portable/blob/c6b94dabcf1a75c1b757547e2325a6b4c7ba0f48/miniwin/src/internal/d3drmrenderer_sdl3gpu.h#L123)
> 
> Line 123 in [c6b94da](/isledecomp/isle-portable/commit/c6b94dabcf1a75c1b757547e2325a6b4c7ba0f48)
> 
>  Direct3DRMRenderer* device = Direct3DRMSDL3GPURenderer::Create(640, 480); 

Adding the "return;" before this line worked.

**Comment by AJenbo** [comment]
@aroenai can you please teset this: https://github.com/isledecomp/isle-portable/pull/552

Make sure that both SDL_GPU and OpenGL works as expected.

**Comment by aroenai** [comment]
Both display, but SDL3 GPU HAL is still showing the credits and transition corruption.
